# Site
name: "Rahul Rade"
title: "Rahul Rade"
description: "My Personal Website"
meta_description: "My Personal Website"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 6
paginate_path: "/projects/page:num/"
baseurl: '/'
email: 'rsrade14@gmail.com'
google_analytics: 'UA-141139264-1'
disqus: 'myrah'
# sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  imrahulr:
    name: Rahul Rade
    display_name: Rahul
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: rsrade14@gmail.com
    web: https://www.linkedin.com/in/rsrade/
    twitter: https://twitter.com/ImRahulR97
    description: "Machine Learning Enthusiast"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge