# Site
name: "Dipam Paul"
title: "Dipam Paul"
description: "My Personal Website"
meta_description: "My Personal Website"
logo: 'assets/images/logo.png'
favicon: 'a0d3733d8893d70aa12a6d654823a973.jpg'
paginate: 6
paginate_path: "/projects/page:num/"
baseurl: '/'
email: 'dipampaul17@gmail.com'
google_analytics: 'UA-141139264-1'
disqus: 'myrah'
# sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  imrahulr:
    name: Dipam Paul
    display_name: Dipam 
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: dipampaul17@gmail.com
    web: https://www.linkedin.com/in/dipam-paul-36672b15b/
    twitter: https://twitter.com/theboyfrom_kol
    description: "On a lifelong journey to learn, solve, practice and raconteur with data."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
